# shared definitions for all versions
tests:
  stage: test

  before_script:
    - python --version
    - pip install .[test]

  script:
    - pytest -v

  parallel:
    matrix:
      - PYTHON_VERSION:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  image: "python:$PYTHON_VERSION"

static-code-checks:
  stage: test
  image: "python:3.8"

  before_script:
    - python --version
    - pip install flake8

  script:
    - flake8 src/


# need to set the TWINE_PASSWORD env variable
# in the gitlab ci secrets
pypi:
  image: "python:3.8"
  stage: release
  script:
    - pip install -U twine build
    - python -m build
    - twine upload dist/*
  only:
    - tags
  variables:
    TWINE_USERNAME: "__token__"
    TWINE_REPOSITORY: "testpypi" # remove to upload to actual pypi
