# jobs in the same stage run in parallel
# later stages run after all jobs of previous stage were successfull
stages:
  - static-checks
  - test
  - deploy

flake8:
  stage: static-checks
  image: "python:3.8"

  before_script:
    - python --version
    - pip install flake8

  script:
    - flake8 src/

tests:
  stage: test

  before_script:
    - python --version
    - pip install .[test]

  script:
    - pytest -v

  parallel:
    matrix:
      - PYTHON_VERSION:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  image: "python:$PYTHON_VERSION"

# need to set the TWINE_PASSWORD env variable
# in the gitlab ci secrets
pypi:
  image: "python:3.8"
  stage: deploy
  script:
    - pip install -U twine build
    - python -m build
    - twine upload dist/*
  only:
    - tags
  variables:
    TWINE_NON_INTERACTIVE: "true"
    TWINE_USERNAME: "__token__"
    TWINE_REPOSITORY: "testpypi" # remove to upload to actual pypi
