# shared definitions for all versions
tests:
  stage: test

  before_script:
    - python --version
    - pip install .[test]

  script:
    - pytest -v

  parallel:
    matrix:
      - PYTHON_VERSION:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  image: "python:$PYTHON_VERSION"

static-code-checks:
  stage: test
  image: "python:3.8"

  before_script:
    - python --version
    - pip install flake8

  script:
    - flake8 src/
